name: Render Zcash Protocol Specification
description: GitHub Action to compile ZIPs and also Zcash Protocol Specification LaTeX documents
author: Deirdre Connolly and Daira-Emma Hopwood
runs:
  using: composite
  steps:
    - uses: cachix/install-nix-action@19effe9fe722874e6d46dd7182e4b8b7a43c4a99 # v31.10.0
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - shell: bash
      run: nix develop --command make all
