name: Render ZIPs
description: GitHub Action to compile ZIPs only
author: Deirdre Connolly and Daira-Emma Hopwood
runs:
  using: composite
  steps:
    - uses: DeterminateSystems/nix-installer-action@c5a866b6ab867e88becbed4467b93592bce69f8a # v21
    - uses: DeterminateSystems/magic-nix-cache-action@565684385bcd71bad329742eefe8d12f2e765b39 # v13
    - shell: bash
      run: nix develop --command make all-zips
