# Reference: https://nathan-at-least.github.io/auto-deploy-howto.html
name: Deploy Rendered Site

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  render-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      # Now render to the site:

      # Each deploy overwrites the contents of `gh-pages` branch from
      # `main`, but also introduces a merge structure so that the history of
      # `gh-pages` is tracked:
      - name: Overwrite gh-pages branch with main branch
        run: |
          set -x
          BASE_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
          git config --global user.name 'autodeploy'
          git config --global user.email 'autodeploy'
          git fetch
          TMP='local-temp-branch'
          git checkout -b "$TMP" "$BASE_BRANCH" # Same tree state as main branch
          git merge \
            --strategy ours \
            --commit \
            -m 'Auto-deploy: overwriting with `main` branch' \>>
            --allow-unrelated-histories \
            origin/gh-pages
          git checkout gh-pages
          git merge --ff-only "$TMP"
          git branch -d "$TMP"
          
      - name: Compile ZIPs and Zcash Protocol Specification
        uses: ./.github/actions/render

      - name: Commit and Push render to gh-pages
        uses: EndBug/add-and-commit@v9.1.4
        with:
          add: 'rendered'
          default_author: github_actions