name: Check dependencies of rendered ZIPs

on:
  pull_request:

jobs:
  updatecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      - name: Check dependencies
        shell: bash
        run: |
          set +e
          ./update_check.sh
          exitcode=$?
          if [ "$exitcode" -eq 1 ]; then
            touch neutral.signal
          else
            exit $exitcode
          fi

      - name: Record status
        uses: actions/upload-artifact@v6
        if: hashFiles('neutral.signal') != ''
        with:
          name: neutral-signal
          path: neutral.signal
          retention-days: 1
